import Head from 'next/head'
import Footer from '../components/footer'
import Navbar from '../components/navbar'

export default function Home() {
  return (
    <div className=' bg-slate-900 w-screen h-screen p-5 '>
      <Head>
        <title>AjieSAW Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.icon-icons.com/icons2/1447/PNG/512/32408sushi_98892.png" />
      </Head>

      <Navbar />

      <main>
        
      </main>

      <Footer />

    </div>
  )
}
