import Head from 'next/head'

export default function Home() {
  return (
    <div className=' bg-slate-900 w-screen h-screen '>
      <Head>
        <title>AjieSAW Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn.icon-icons.com/icons2/1447/PNG/512/32408sushi_98892.png" />
      </Head>

      <main>

      </main>

      <footer>
        
      </footer>
    </div>
  )
}
